version: 2
updates:
    # npm / pnpm dependencies
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "monthly"
      target-branch: "main"
      open-pull-requests-limit: 5
      groups:
          production-dependencies:
              dependency-type: "production"
          development-dependencies:
              dependency-type: "development"

    # GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "monthly"
      target-branch: "main"
      open-pull-requests-limit: 5
      groups:
          github-actions:
              patterns:
                  - "*"
