name: CI
on: push
jobs:
    test:
        name: Lint, typecheck
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4.0.1
              with:
                  node-version: "20"
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false
            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
            - name: Setup pnpm cache
              uses: actions/cache@v3
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-
            # Throw an error if the pnpm-lock.yaml file doesn't match the installed dependencies
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Lint
              run: pnpm lint
